version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

env:
  - PACKAGE_PATH=github.com/jack-kitto/secretly-sdk/cmd

builds:
- binary: "{{ .ProjectName }}"
  main: ./cmd/sdk
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X {{.Env.PACKAGE_PATH}}={{.Version}} 

universal_binaries:
- replace: true

archives:
  - name_template: >
      {{- .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  prerelease: false
  make_latest: true
  mode: append
  header: |
    ## Secretly SDK ({{ .Date }})

    Welcome to this new release!
  footer: |
    ## Thanks

    Those were the changes on {{ .Tag }}!

  include_meta: true
